### PR TITLE
Use https when possible.

### PR DESCRIPTION
**Pull request by XhmikosR**
This is a pretty big patch, but should be straight-forward to review :)

Will probably need a rebase after #182. Also, I left a few remaining http links for someone else later.

Let me know if there's something that needs to be changed.

### CODE REVIEW

**Comment by khalwat** [comment]
I really appreciate the effort; I'm not sure this is something I should be doing, though.  The URLs on schema.org are also essentially unique key. So for instance, look here:

https://schema.org/Review

Note that it says on the page:

**Canonical URL:** http://schema.org/Review

...and have a look at their JSON-LD examples:

```
<script type="application/ld+json">
{
  "@context": "http://schema.org/",
  "@type": "Review",
  "reviewBody": "The restaurant has great ambiance.",
  "itemReviewed": {
    "@type": "Restaurant",
    "name": "Fine Dining Establishment"
  },
  "reviewRating": {
    "@type": "Rating",
    "ratingValue": 5,
    "worstRating": 1,
    "bestRating": 5,
    "reviewAspect": "Ambiance"
  }
}
</script>
```

So while I agree we generally want https -- this is a bit of a special case I think.

**Comment by XhmikosR** [comment]
I don't agree with you, @khalwat. Their canonical URL is just a leftover since they clearly redirect to https.

Either way, there are many more changes, so please don't close this, I can rebase it if needed.

**Comment by khalwat** [comment]
In the JSON-LD, the `@context` is used to indicate the context of the vocabulary. It's not clear to me if https is valid or correct for that, though I did run it through the [Structured Data Testing Tool](https://search.google.com/structured-data/testing-tool) and it seems to validate.

Here's a FAQ I found: https://schema.org/docs/faq.html#19

**Q: Should we write 'https://schema.org' or 'http://schema.org' in our markup?**

> There is a general trend towards using 'https' more widely, and you can already write 'https://schema.org' in your structured data. Over time we will migrate the schema.org site itself towards using https: as the default version of the site and our preferred form in examples. However 'http://schema.org' -based URLs in structured data markup will remain widely understood for the forseeable future and there should be no urgency about migrating existing data. This is a lengthy way of saying that both 'https://schema.org' and 'http://schema.org' are fine.

...so I will re-open it based on that. Just understand that it's not the same as using https on a live website (which is obviously a best practice).

**Comment by XhmikosR** [comment]
@khalwat: are you sure my patch changes that? Because I tried exactly to not change those.

**Comment by XhmikosR** [comment]
If you clone my fork and check out the branch locally, you should see there are a few more `http` links. SVGs, and the schema output links. If I accidentally changed the LD output, let me know which change it's exactly and I will revert that :)

This patch was to change all the http links that don't affect the LD output.

**Comment by khalwat** [comment]
hmmmmm. I scanned the diff, and could swear I saw places where it did. But perhaps I was wrong.

Either way, according to schema.org, it doesn't matter 👍

**Comment by XhmikosR** [comment]
My plan is to not touch that, though, at least not in this PR. Can you quickly try this branch and confirm?

EDIT:

Here's a quick visual diff since GitHub doesn't allow to view the whole patch: https://gist.github.com/XhmikosR/960aa5f699ab6096827e653f8f74017c

**Comment by XhmikosR** [comment]
Here's a quick view since GitHub doesn't allow to view the whole patch here https://gist.github.com/XhmikosR/960aa5f699ab6096827e653f8f74017c

**Comment by khalwat** [comment]
Yep, seems good. Let me know when you feel you're done with this PR?

**Comment by XhmikosR** [comment]
Oh, I'm done, as long as we verify the output does not change :)

The remaining http links, you can tackle them yourself if needed.

**Comment by khalwat** [comment]
So I've actually decided it's best not to use this PR; the reason is twofold that so many files are touched, it's going to take a significant amount of time to sanity check everything, without much gain.

More importantly, all of these classes are actually auto-generated by a scraping script that I wrote which pulls the data down from schema.org. I consider schema.org to be the "source of truth" for these vocabularies; so when they update to use https, I will as well.

I do appreciate the effort you undertook in doing all of this, however, so thank you for that.

**Comment by XhmikosR** [comment]
@khalwat Still, there is **absolutely** no reason for you not to use https for the various frontend scripts like GTM.

**Comment by khalwat** [comment]
This is what it does for GTM:

```
                    'googleTagManagerUrl' => [
                        'title' => 'Google Tag Manager Script URL',
                        'instructions' => 'The URL to the Google Tag Manager script. Normally this should not be changed, unless you locally cache it.',
                        'type' => 'string',
                        'value' => '//www.googletagmanager.com/gtm.js',
                    ],
                    'googleTagManagerNoScriptUrl' => [
                        'title' => 'Google Tag Manager Script &lt;noscript&gt; URL',
                        'instructions' => 'The URL to the Google Tag Manager `&lt;noscript&gt;`. Normally this should not be changed, unless you locally cache it.',
                        'type' => 'string',
                        'value' => '//www.googletagmanager.com/ns.html',
                    ],
```

These are protocol-less URLs, as recommended by Google as the way to include these scripts. If you're on a `https` page, then it will use `https`. If you're not, then it will use `http`

I don't understand the complaint here.

**Comment by XhmikosR** [comment]
The complaint is protocol-relative URLs != https.

**Comment by khalwat** [comment]
I'm using what Google is recommending that I use. If they change their recommendation, I will change the URLs.

**Comment by XhmikosR** [comment]
There is no way Google is suggesting protocol relative URLs in 2018 ;)

https://developers.google.com/tag-manager/quickstart

**Comment by khalwat** [comment]
This definitely wasn't the case 6 months ago or so when those were put in, so it's a recent change in their recommendations.

Now that they have changed their recommendation, I've updated the default settings: https://github.com/nystudio107/craft-seomatic/commit/24cd2320316c820749b0b96a59a6c3f98e002a7c

**Pull request closed without merging**
