### PR TITLE
Solspace calendar integration error

### PR DESCRIPTION
**Pull request by umkasanki**
### Description
I have an error on trying to delete Calendar.
```
{"name":"Exception","message":"Argument 1 passed to nystudio107\\seomatic\\seoelements\\SeoEvent::nystudio107\\seomatic\\seoelements\\{closure}() must be an instance of Solspace\\Calendar\\Events\\SaveModelEvent, instance of Solspace\\Calendar\\Events\\DeleteModelEvent given","code":0,"error":"Argument 1 passed to nystudio107\\seomatic\\seoelements\\SeoEvent::nystudio107\\seomatic\\seoelements\\{closure}() must be an instance of Solspace\\Calendar\\Events\\SaveModelEvent, instance of Solspace\\Calendar\\Events\\DeleteModelEvent given","exception":"TypeError","file":"C:\\OpenServer\\domains\\craft\\vendor\\nystudio107\\craft-seomatic\\src\\seoelements\\SeoEvent.php","line":98,"trace":[{"function":"nystudio107\\seomatic\\seoelements\\{closure}","class":"nystudio107\\seomatic\\seoelements\\SeoEvent","type":"::"},{"file":"C:\\OpenServer\\domains\\craft\\vendor\\yiisoft\\yii2\\base\\Event.php","line":312,"function":"call_user_func"},{"file":"C:\\OpenServer\\domains\\craft\\vendor\\yiisoft\\yii2\\base\\Component.php","line":642,"function":"trigger","class":"yii\\base\\Event","type":"::"},{"file":"C:\\OpenServer\\domains\\craft\\vendor\\solspace\\craft-calendar\\packages\\plugin\\src\\Services\\CalendarsService.php","line":375,"function":"trigger","class":"yii\\base\\Component","type":"->"},{"file":"C:\\OpenServer\\domains\\craft\\vendor\\solspace\\craft-calendar\\packages\\plugin\\src\\Controllers\\CalendarsController.php","line":331,"function":"deleteCalendarById","class":"Solspace\\Calendar\\Services\\CalendarsService","type":"->"},{"function":"actionDelete","class":"Solspace\\Calendar\\Controllers\\CalendarsController","type":"->"},{"file":"C:\\OpenServer\\domains\\craft\\vendor\\yiisoft\\yii2\\base\\InlineAction.php","line":57,"function":"call_user_func_array"},{"file":"C:\\OpenServer\\domains\\craft\\vendor\\yiisoft\\yii2\\base\\Controller.php","line":178,"function":"runWithParams","class":"yii\\base\\InlineAction","type":"->"},{"file":"C:\\OpenServer\\domains\\craft\\vendor\\yiisoft\\yii2\\base\\Module.php","line":552,"function":"runAction","class":"yii\\base\\Controller","type":"->"},{"file":"C:\\OpenServer\\domains\\craft\\vendor\\craftcms\\cms\\src\\web\\Application.php","line":293,"function":"runAction","class":"yii\\base\\Module","type":"->"},{"file":"C:\\OpenServer\\domains\\craft\\vendor\\craftcms\\cms\\src\\web\\Application.php","line":602,"function":"runAction","class":"craft\\web\\Application","type":"->"},{"file":"C:\\OpenServer\\domains\\craft\\vendor\\craftcms\\cms\\src\\web\\Application.php","line":272,"function":"_processActionRequest","class":"craft\\web\\Application","type":"->"},{"file":"C:\\OpenServer\\domains\\craft\\vendor\\yiisoft\\yii2\\base\\Application.php","line":384,"function":"handleRequest","class":"craft\\web\\Application","type":"->"},{"file":"C:\\OpenServer\\domains\\craft\\web\\index.php","line":19,"function":"run","class":"yii\\base\\Application","type":"->"}]}
```

Fixed by replace `SaveModelEvent` method  with`DeleteModelEvent`

**Before fix:**

https://user-images.githubusercontent.com/496132/210323268-347ec598-1820-4810-a6d3-c38ec08e8dbe.mp4

**After fix:**

https://user-images.githubusercontent.com/496132/210323522-edc5a29b-5f4b-42f5-b0d6-1053c0907316.mp4

Thanks @Romanavr

### CODE REVIEW

**Comment by khalwat** [comment]
Thanks!

**Comment by umkasanki** [comment]
Hello @khalwat
In one of our projects, this is a breaking bug. Could you let us know when you will be able to release this fix for Craft 3.X?
We don't want to disable SEOmatic ;)

**Comment by Romanavr** [comment]
Hello @khalwat

In one of our projects, this is a breaking bug. Could you let us know when you will be able to release this fix for Craft 3.X?
We don't want to disable SEOmatic ;)

**Comment by khalwat** [comment]
Yep sure, will do tonight or tomorrow!

**Pull request merged**
