### PR TITLE
Fix a compatibility issue with Feed Me

### PR DESCRIPTION
**Pull request by olivierbon**

### CODE REVIEW

**Comment by khalwat** [comment]
Is this intended for the Craft 3 or Craft 4 version of SEOmatic/Feed Me? 

The Craft 4 version of SEOmatic already has these fixes in place:

https://github.com/nystudio107/craft-seomatic/blob/develop-v4/src/integrations/feedme/SeoSettings.php#L51

https://github.com/nystudio107/craft-seomatic/blob/develop-v4/src/integrations/feedme/SeoSettings.php#L43

**Comment by khalwat** [comment]
Thx for the PR! Already taken care of tho

**Comment by robzor** [comment]
Craft 4, Oli logged this as I was having a 500 error in Feed Me 5.0.2 today.

SEOMatic is at 4.0.0-beta.8

**Comment by khalwat** [comment]
Please update to the release version of SEOmatic for Craft CMS 4. It's at version `4.0.0` currently. https://github.com/nystudio107/craft-seomatic/releases/tag/4.0.0

**Comment by robzor** [comment]
Oh, weird. My 'Updates' tab in Utilities didn't have the 'you have new stuff' badge so I hadn't noticed. Thanks! :)

**Comment by khalwat** [comment]
Would suggest using the CLI to update:

https://nystudio107.com/blog/updating-craft-cms-without-headaches#4-embrace-composer

**Pull request closed without merging**
