### PR TITLE
Don't force jpg for SEO images

### PR DESCRIPTION
**Pull request by timkelty**
We had a client creating PNGs for SEO images that ended up looking bad because they were converted to jpg.

### CODE REVIEW

**Comment by khalwat** [comment]
mmmmm. So this is kinda done on purpose, to client-proof things so that a client doesn't upload a massive PNG image to be used as the Twitter Card or `ogImage`

It's not just that a large file size would be bad... it's that both Twitter and Facebook have size limitations on said files, and they will just refuse to use them in that case.

So how can we keep this client-proofing in, but allow things to work the way you want them to @timkelty ? Certainly you could just manually set it via Twig, but that seems a bit weak.

**Comment by timkelty** [comment]
Well you're still resizing dimensions, so it seems like even if they upload a huge png, the resized one will be reasonable.

I'd also bet that most services (imgix/thumbor) are going to do any lossless compression it can be default.

**Comment by khalwat** [comment]
There was one other reason, and this is just FYI -- it's so that people can use an SVG or other file formats that Twitter and Facebook both do not support when uploading their SEO images.

**Comment by timkelty** [comment]
Hmmm- Imgix and Craft will generate a raster from an SVG? Pretty sure Thumbor won’t do that.

**Comment by khalwat** [comment]
Yep, I was surprised too that Craft can do it. I'm not 100% sure on Imgix tbh tho

**Comment by khalwat** [comment]
I'm not opposed to the _idea_ of this, but what if instead of just blindly using whatever format is passed in, it allows for incoming files to be in `jpg` or `png` formats, but for anything else, it forces it to `jpg`?

**Comment by timkelty** [comment]
> I'm not opposed to the idea of this, but what if instead of just blindly using whatever format is passed in, it allows for incoming files to be in jpg or png formats, but for anything else, it forces it to jpg?

Sounds reasonable to me!

**Comment by khalwat** [comment]
So... you want to revise the PR, or should I close it?

**Comment by timkelty** [comment]
I'll revise it.

**Comment by khalwat** [comment]
I think you wanted me to do this instead @timkelty ?

**Comment by khalwat** [comment]
Implemented in https://github.com/nystudio107/craft-seomatic/commit/7e54f2d59e6246deca7f0d76b38709e74b183868

**Comment by timkelty** [comment]
Thanks @khalwat!

**Pull request closed without merging**
