### PR TITLE
Lossy compression of the resources images.

### PR DESCRIPTION
**Pull request by XhmikosR**
Before: 3,31 MB (3.478.445 bytes)
After:  1,47 MB (1.542.359 bytes)

Note that even though this is lossy compression, there shouldn't be any visible changes. And we save more than 50% :)

### CODE REVIEW

**Comment by XhmikosR** [comment]
Note that even though this is lossy compression, there shouldn't be any visible changes. And we save more than 50% :)

**Comment by khalwat** [comment]
None of these resources are loaded on the frontend; they are just in the documentation. That will reduce the size of the downloaded documentation for sure, but...

I'm working on moving the docs over to a proper website with search functionality, etc. so it may be largely irrelevant?

**Comment by khalwat** [comment]
I do run these resources through ImageOptim before committing them btw. But obviously that will never be as good as lossy compression.

**Comment by XhmikosR** [comment]
Hey, I know, I just thought we could make the README load faster since the savings are quite big :)

**Comment by khalwat** [comment]
If I weren't moving all of this anyway, I'd certainly look into it. Thank you for your efforts, but I think this one I have other plans for.

**Pull request closed without merging**
